###########################################################################
#
# Simple-Servo Makefile
#
###########################################################################

TARGET	= Simple-Servo-2

COMMON_OBJS = a2d_8.o Timer.o UART.o Hardware.o Servo.o

include ../Rules.mk

